#!/usr/bin/env bash
ghc -O2 factorio-module-selector  -Wall -Wno-missing-signatures -Wno-name-shadowing -Wno-unused-top-binds -Wno-unused-imports -threaded -rtsopts && time ./factorio-module-selector +RTS -N
# ghc -O2 factorio-module-selector -rtsopts && time ./factorio-module-selector
